<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../uCredit.Infrastructure.LegacySql/uCredit.Infrastructure.LegacySql.csproj" />
    <ProjectReference Include="../uCredit.Infrastructure.Identity/uCredit.Infrastructure.Identity.csproj" />
    <ProjectReference Include="../uCredit.Modules.Branding/uCredit.Modules.Branding.csproj" />
    <ProjectReference Include="../uCredit.Modules.Contracts/uCredit.Modules.Contracts.csproj" />
    <ProjectReference Include="../uCredit.Modules.Customers/uCredit.Modules.Customers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
